title: Troy C Frost
logo: C:\\Users\\troyc\\Downloads\u5972237738_httpss.mj.run21kn6Q6DMus_httpss.mj.rune5NUrpjhQLg_f3b4234d-e9b3-4976-88fe-5b8fa37352cd_0.png
description: |
  Welcome to my GitHub page! I am passionate about machine learning, AI, and technology. Explore my projects, repositories, and insights.
show_downloads: true
theme: jekyll-theme-cayman
