title: Troy C Frost
#logo: C:\\Users\\troyc\\Downloads\\u5972237738_httpss.mj.runGQNphADKT6c_httpss.mj.runPejs_r93Zxg_h_2762d853-a461-4036-8af3-468fee999207.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
